/**
 * Created by wanglei on 16/11/3.
 */
// 显示/隐藏 Header
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';

export const SHOW_LEFT_MENU = 'SHOW_LEFT_MENU';
export const CHANGE_LOAD_SHOW_STATE = 'CHANGE_LOAD_SHOW_STATE';
export const CLOSE_PROMPTD_DIALOG_BOX = 'CLOSE_PROMPTD_DIALOG_BOX';
export const OPEN_SUCCESS_PROMPTD_DIALOG_BOX = 'OPEN_SUCCESS_PROMPTD_DIALOG_BOX';
export const OPEN_FAULT_PROMPTD_DIALOG_BOX = 'OPEN_FAULT_PROMPTD_DIALOG_BOX';
export const CLOSE_ENLARGED_PICTURE_BOX = 'CLOSE_ENLARGED_PICTURE_BOX';
export const OPEN_ENLARGED_PICTURE_BOX = 'OPEN_ENLARGED_PICTURE_BOX';
export const OPEN_OPERATE_DIALOG_BOX = 'OPEN_OPERATE_DIALOG_BOX';
export const CLOSE_OPERATE_DIALOG_BOX = 'CLOSE_OPERATE_DIALOG_BOX';
export const SURE_OPERATE_DIALOG_BOX = 'SURE_OPERATE_DIALOG_BOX';

export const OPEN_MINI_OPERATE_DIALOG_BOX = 'OPEN_MINI_OPERATE_DIALOG_BOX';
export const CONFIRM_MINI_OPERATE_DIALOG_BOX = 'CONFIRM_MINI_OPERATE_DIALOG_BOX';
export const CANCEL_MINI_OPERATE_DIALOG_BOX = 'CANCEL_MINI_OPERATE_DIALOG_BOX';
export const CLOSE_MINI_OPERATE_DIALOG_BOX = 'CLOSE_MINI_OPERATE_DIALOG_BOX';

export const OPEN_AUTO_CLOSE_DIALOG_BOX = 'OPEN_AUTO_CLOSE_DIALOG_BOX';
export const CLOSE_AUTO_CLOSE_DIALOG_BOX = 'CLOSE_AUTO_CLOSE_DIALOG_BOX';
export const SHOW_AUTO_CLOSE_WARNING_DIALOG_BOX = 'SHOW_AUTO_CLOSE_WARNING_DIALOG_BOX';
export const HIDE_AUTO_CLOSE_WARNING_DIALOG_BOX = 'HIDE_AUTO_CLOSE_WARNING_DIALOG_BOX';
export const SHOW_SAVE_SUCCESS_DIALOG_BOX = 'SHOW_SAVE_SUCCESS_DIALOG_BOX';
export const HIDE_SAVE_SUCCESS_DIALOG_BOX = 'HIDE_SAVE_SUCCESS_DIALOG_BOX';
export const OPEN_NO_AUTHORIZATION_DIALOG_BOX = 'OPEN_NO_AUTHORIZATION_DIALOG_BOX';

